#!/bin/bash
clear
#——————————————————
# Created By @StarZany ☆ @star_Jani
# VERSION 1.3
# SLOW DNS TUNNEL
#——————————————————
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
CORTITLE='\033[1;41m'
DIR='/etc/SSHPlus/dns'
SCOLOR='\033[0m'

configdns() {
    interface=$(ip a | awk '/state UP/{print $2}' | cut -d: -f1)
    iptables -F >/dev/null 2>&1
    iptables -I INPUT -p udp --dport 5300 -j ACCEPT
    iptables -t nat -I PREROUTING -i $interface -p udp --dport 53 -j REDIRECT --to-ports 5300
    ip6tables -I INPUT -p udp --dport 5300 -j ACCEPT
    ip6tables -t nat -I PREROUTING -i $interface -p udp --dport 53 -j REDIRECT --to-ports 5300
}

        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
        echo -e "${CORTITLE}              ☞ SLOWDNS ᵇʸ @StarZany ☆ @star_Jani  ☜          ${SCOLOR}"
        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
installslowdns() {
echo -e ""
echo -e "\033[1;31mATENCAO! \033[1;33mBE AWARE THAT THIS METHOD IS STILL !\033[0m"
echo -e "\n${YELLOW}THIS IS IN THE BETA PHASE AND THAT BEING SLOW MAY NOT WORK PERFECTLY ! ${SCOLOR}\n"
echo -ne "${GREEN}WISHES TO CONTINUE INSTALLATION ? ${YELLOW}[s/n]:${SCOLOR} "
    read resp
    [[ "$resp" != @(s|sim|S|SIM) ]] && {
        echo -e "\n${RED}Returning...${SCOLOR}"
        sleep 2
        conexao
    }
    mkdir /etc/SSHPlus/dns >/dev/null 2>&1
    wget -P $DIR https://raw.githubusercontent.com/starrising321/SSHPLUS/main/dns-server/dns-server >/dev/null 2>&1
    chmod 777 $DIR/dns-server >/dev/null 2>&1
    $DIR/dns-server -gen-key -privkey-file $DIR/server.key -pubkey-file $DIR/server.pub >/dev/null 2>&1
    configdns >/dev/null 2>&1
    cat /dev/null >~/.bash_history && history -c
}
initslow() {
    [[ $(ss -lu | grep -wc '5300') != '0' ]] && {
        echo -e "\n${RED}[${CYAN}1${RED}] ${YELLOW}STOP SLOWDNS${SCOLOR}"
        echo -e "${RED}[${CYAN}2${RED}] ${YELLOW}REMOVE SLOWDNS${SCOLOR}"
        echo -e "${RED}[${CYAN}3${RED}] ${YELLOW}VIEW INFORMATION${SCOLOR}"
        echo -e "${RED}[${CYAN}0${RED}] ${YELLOW}BACK${SCOLOR}"
        echo -ne "\n${GREEN}INFORMATION OPTION${SCOLOR}: "
        read op
        if [[ "$op" == '1' ]]; then
            screen -r -S "slow_dns" -X quit >/dev/null 2>&1
            screen -wipe >/dev/null 2>&1
            sed -i '/5300/d' /etc/autostart >/dev/null 2>&1
            sed -i '/slow_dns/d' /etc/SSHPlus/dns/autodns >/dev/null 2>&1
            echo -e "\n${RED}SLOWDNS OFF !${SCOLOR}"
            sleep 2
            conexao
        elif [[ "$op" == '2' ]]; then
            screen -r -S "slow_dns" -X quit >/dev/null 2>&1
            screen -wipe >/dev/null 2>&1
            sed -i '/5300/d' /etc/autostart >/dev/null 2>&1
            rm -rf /etc/SSHPlus/dns >/dev/null 2>&1
            echo -e "\n${RED}SLOWDNS REMOVED !${SCOLOR}"
            sleep 2
            conexao
        elif [[ "$op" == '3' ]]; then
            [[ -e $DIR/server.pub ]] && keypub=$(cat $DIR/server.pub) || keypub='Null'
            [[ -e $DIR/autodns ]] && nameserver=$(grep -w 'server.key' /etc/SSHPlus/dns/autodns | awk -F' ' '{print $9}') || nameserver='Null'
            tmx='curl -sO https://raw.githubusercontent.com/starrising321/SSHPLUS/main/dns-server/slowdns && chmod +x slowdns && ./slowdns'
            clear
        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
        echo -e "${CORTITLE}              ☞ SLOWDNS ᵇʸ @StarZany ☆ @star_Jani  ☜          ${SCOLOR}"
        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
            echo -e "\n${YELLOW}NAMESERVER(NS)${SCOLOR}: $nameserver"
            echo -e "${YELLOW}PUBLIC KEY${SCOLOR}: $keypub"
            echo -e "\n${GREEN}COMMAND TERMUX${SCOLOR}: ${tmx} ${nameserver} ${keypub}"
            echo -ne "\n${RED}ENTER${YELLOW} return to${GREEN} MENU!${SCOLOR}"
            read
            conexao
        elif [[ "$op" == '0' ]]; then
            sleep 1
            conexao
        else
            echo -e "\n${RED}INVALID OPTION${SCOLOR}"
            sleep 1.5
            conexao
        fi
    } || {
        clear
        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
        echo -e "${CORTITLE}              ☞ SLOWDNS ᵇʸ @StarZany ☆ @star_Jani  ☜          ${SCOLOR}"
        echo -e "${CORTITLE}◆═════════════════════════════════════════════════════════════◆${SCOLOR}"
        echo -ne "\n${GREEN}INFORMATION DOMAIN NS${SCOLOR}: "
        read ns
        [[ -z "$ns" ]] && {
            echo -e "\n${RED}INVALID DOMAIN${SCOLOR}"
            sleep 1.5
            initslow
        }
        echo -e "\n${RED}[${CYAN}1${RED}] ${YELLOW}SLOWDNS SSH${SCOLOR}"
        echo -e "${RED}[${CYAN}2${RED}] ${YELLOW}SLOWDNS SSL${SCOLOR}"
        echo -e "${RED}[${CYAN}3${RED}] ${YELLOW}SLOWDNS SSLH${SCOLOR}"
        echo -e "${RED}[${CYAN}4${RED}] ${YELLOW}SLOWDNS OPENVPN${SCOLOR}"
        echo -e "${RED}[${CYAN}0${RED}] ${YELLOW}BACK${SCOLOR}"
        echo -ne "\n${GREEN}INFORMATION OPTION${SCOLOR}: "
        read opcc
        if [[ "$opcc" == '1' ]]; then
            ptdns='22'
        elif [[ "$opcc" == '2' ]]; then
            ptdns=$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2)
            [[ $ptdns == '' ]] && {
                echo -e "\n${RED}FIRST INSTALL SSL TUNNEL !${SCOLOR}"
                sleep 1.5
                initslow
            }
        elif [[ "$opcc" == '3' ]]; then
            ptdns=$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2)
            [[ $ptdns == '' ]] && {
                echo -e "\n${RED}FIRST INSTALL SSLH !${SCOLOR}"
                sleep 1.5
                initslow
            }
        elif [[ "$opcc" == '4' ]]; then
            [[ ! -e /etc/openvpn/server.conf ]] && {
                echo -e "\n${RED}FIRST INSTALL OPENVPN !${SCOLOR}"
                sleep 1.5
                initslow
            } || {
                ptdns=$(sed -n 1p /etc/openvpn/server.conf| cut -d' ' -f2)
            }
        elif [[ "$opcc" == '0' ]]; then
            sleep 1.5
            conexao
        else
            echo -e "\n${RED}INVALID OPTION${SCOLOR}"
            sleep 1.5
            initslow
        fi
        screen -dmS slow_dns $DIR/dns-server -udp :5300 -privkey-file $DIR/server.key ${ns} 0.0.0.0:${ptdns} >/dev/null 2>&1
        keypub=$(cat $DIR/server.pub)
        cd $HOME
        echo -e "\n${YELLOW}SLOWDNS ON...${SCOLOR}"
        [[ ! -e /etc/iptables/rules.v4 ]] && {
            configdns > /dev/null 2>&1
            DEBIAN_FRONTEND=noninteractive apt install -y iptables-persistent >/dev/null 2>&1
        } || {
            sleep 2
            configdns > /dev/null 2>&1
            iptables-save > /etc/iptables/rules.v4
        }
        echo "screen -dmS slow_dns $DIR/dns-server -udp :5300 -privkey-file $DIR/server.key ${ns} 0.0.0.0:${ptdns}" >/etc/SSHPlus/dns/autodns
        chmod 777 /etc/SSHPlus/dns/autodns >/dev/null 2>&1
        echo "ss -lu|grep -w '5300' || /etc/SSHPlus/dns/autodns" >>/etc/autostart
        tmx='curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns'
        echo -e "\n${GREEN}SLOWDNS ATIVADO !${SCOLOR}"
        echo -e "\n${YELLOW}COMANDO TERMUX${SCOLOR}: ${tmx} ${ns} ${keypub}"
        echo -ne "\n${RED}ENTER${YELLOW} para retornar ao${GREEN} MENU!${SCOLOR}"
        read
        conexao
    }
}
[[ -d $DIR ]] && {
    initslow
} || {
    installslowdns
    sleep 0.5
    initslow
}
